### ISSUE TITLE
Vanishing LS - (CryoTank)

### ISSUE THREAD

**Issue by garithmar** [ScienceFun/Kerbalism-Continued#8]
Supplies vanish from craft and radiation/stress/co2 levels max out very fast.  

Modlist
[Modlist.txt](https://github.com/ScienceFun/Kerbalism-Continued/files/1700785/Modlist.txt)
Log File
[KSP.zip](https://github.com/ScienceFun/Kerbalism-Continued/files/1700790/KSP.zip)

**Comment by HaullyGames** [comment]
Hi,

This bug is because an incompatibility with the ** CryoTank ** mod.
I will add a new project to review the compatibility, but this will take time to correct, when corrected, we may find another incompatibility.

Details for project.
When the error below happened, it break "vessel_resources" method, this is a mainly method in Kerbalism.
After this, we have an invalid Key for the "KERBALISM.resource_info" dictionary.

``[EXC 13:00:20.049] ArgumentNullException: Argument cannot be null.
Parameter name: key
	System.Collections.Generic.Dictionary`2[System.String,KERBALISM.resource_info].TryGetValue (System.String key, KERBALISM.resource_info& value)
	KERBALISM.vessel_resources.Info (.Vessel v, System.String resource_name)
	KERBALISM.Background.ProcessCryoTank (.Vessel v, .ProtoPartSnapshot p, .ProtoPartModuleSnapshot m, .PartModule simple_boiloff, KERBALISM.vessel_resources resources, Double elapsed_s)
	KERBALISM.Background.update (.Vessel v, KERBALISM.vessel_info vi, KERBALISM.VesselData vd, KERBALISM.vessel_resources resources, Double elapsed_s)
	KERBALISM.Kerbalism.FixedUpdate ()``

**Comment by garithmar** [comment]
I'll remove that mod and see if anything does it again.

**Comment by garithmar** [comment]
alright removing just cry tanks got rid of the problem and no errors as of yet.  Due to the amount of mods I run i'll continue to watch for any errors and let you know.

**Comment by HaullyGames** [comment]
CryoTank Compatibility has been fixed.
